//+build mmal

package mmal

////////////////////////////////////////////////////////////////////////////////
// CGO

/*
#cgo pkg-config: mmal
#include <interface/mmal/mmal.h>
*/
import "C"

////////////////////////////////////////////////////////////////////////////////
// TYPES

type (
	MMALEncodingType uint32
)

////////////////////////////////////////////////////////////////////////////////
// VIDEO ENCODINGS

var (
	MMAL_ENCODING_H264   MMALEncodingType = C.MMAL_ENCODING_H264
	MMAL_ENCODING_MVC    MMALEncodingType = C.MMAL_ENCODING_MVC
	MMAL_ENCODING_H263   MMALEncodingType = C.MMAL_ENCODING_H263
	MMAL_ENCODING_MP4V   MMALEncodingType = C.MMAL_ENCODING_MP4V
	MMAL_ENCODING_MP2V   MMALEncodingType = C.MMAL_ENCODING_MP2V
	MMAL_ENCODING_MP1V   MMALEncodingType = C.MMAL_ENCODING_MP1V
	MMAL_ENCODING_WMV3   MMALEncodingType = C.MMAL_ENCODING_WMV3
	MMAL_ENCODING_WMV2   MMALEncodingType = C.MMAL_ENCODING_WMV2
	MMAL_ENCODING_WMV1   MMALEncodingType = C.MMAL_ENCODING_WMV1
	MMAL_ENCODING_WVC1   MMALEncodingType = C.MMAL_ENCODING_WVC1
	MMAL_ENCODING_VP8    MMALEncodingType = C.MMAL_ENCODING_VP8
	MMAL_ENCODING_VP7    MMALEncodingType = C.MMAL_ENCODING_VP7
	MMAL_ENCODING_VP6    MMALEncodingType = C.MMAL_ENCODING_VP6
	MMAL_ENCODING_THEORA MMALEncodingType = C.MMAL_ENCODING_THEORA
	MMAL_ENCODING_SPARK  MMALEncodingType = C.MMAL_ENCODING_SPARK
	MMAL_ENCODING_MJPEG  MMALEncodingType = C.MMAL_ENCODING_MJPEG
)

////////////////////////////////////////////////////////////////////////////////
// IMAGE ENCODINGS

var (
	MMAL_ENCODING_JPEG MMALEncodingType = C.MMAL_ENCODING_JPEG
	MMAL_ENCODING_GIF  MMALEncodingType = C.MMAL_ENCODING_GIF
	MMAL_ENCODING_PNG  MMALEncodingType = C.MMAL_ENCODING_PNG
	MMAL_ENCODING_PPM  MMALEncodingType = C.MMAL_ENCODING_PPM
	MMAL_ENCODING_TGA  MMALEncodingType = C.MMAL_ENCODING_TGA
	MMAL_ENCODING_BMP  MMALEncodingType = C.MMAL_ENCODING_BMP
)

////////////////////////////////////////////////////////////////////////////////
// UNCOMPRESSED ENCODINGS

var (
	MMAL_ENCODING_I420        MMALEncodingType = C.MMAL_ENCODING_I420
	MMAL_ENCODING_I420_SLICE  MMALEncodingType = C.MMAL_ENCODING_I420_SLICE
	MMAL_ENCODING_YV12        MMALEncodingType = C.MMAL_ENCODING_YV12
	MMAL_ENCODING_I422        MMALEncodingType = C.MMAL_ENCODING_I422
	MMAL_ENCODING_I422_SLICE  MMALEncodingType = C.MMAL_ENCODING_I422_SLICE
	MMAL_ENCODING_YUYV        MMALEncodingType = C.MMAL_ENCODING_YUYV
	MMAL_ENCODING_YVYU        MMALEncodingType = C.MMAL_ENCODING_YVYU
	MMAL_ENCODING_UYVY        MMALEncodingType = C.MMAL_ENCODING_UYVY
	MMAL_ENCODING_VYUY        MMALEncodingType = C.MMAL_ENCODING_VYUY
	MMAL_ENCODING_NV12        MMALEncodingType = C.MMAL_ENCODING_NV12
	MMAL_ENCODING_NV21        MMALEncodingType = C.MMAL_ENCODING_NV21
	MMAL_ENCODING_ARGB        MMALEncodingType = C.MMAL_ENCODING_ARGB
	MMAL_ENCODING_ARGB_SLICE  MMALEncodingType = C.MMAL_ENCODING_ARGB_SLICE
	MMAL_ENCODING_RGBA        MMALEncodingType = C.MMAL_ENCODING_RGBA
	MMAL_ENCODING_RGBA_SLICE  MMALEncodingType = C.MMAL_ENCODING_RGBA_SLICE
	MMAL_ENCODING_ABGR        MMALEncodingType = C.MMAL_ENCODING_ABGR
	MMAL_ENCODING_ABGR_SLICE  MMALEncodingType = C.MMAL_ENCODING_ABGR_SLICE
	MMAL_ENCODING_BGRA        MMALEncodingType = C.MMAL_ENCODING_BGRA
	MMAL_ENCODING_BGRA_SLICE  MMALEncodingType = C.MMAL_ENCODING_BGRA_SLICE
	MMAL_ENCODING_RGB16       MMALEncodingType = C.MMAL_ENCODING_RGB16
	MMAL_ENCODING_RGB16_SLICE MMALEncodingType = C.MMAL_ENCODING_RGB16_SLICE
	MMAL_ENCODING_RGB24       MMALEncodingType = C.MMAL_ENCODING_RGB24
	MMAL_ENCODING_RGB24_SLICE MMALEncodingType = C.MMAL_ENCODING_RGB24_SLICE
	MMAL_ENCODING_RGB32       MMALEncodingType = C.MMAL_ENCODING_RGB32
	MMAL_ENCODING_RGB32_SLICE MMALEncodingType = C.MMAL_ENCODING_RGB32_SLICE
	MMAL_ENCODING_BGR16       MMALEncodingType = C.MMAL_ENCODING_BGR16
	MMAL_ENCODING_BGR16_SLICE MMALEncodingType = C.MMAL_ENCODING_BGR16_SLICE
	MMAL_ENCODING_BGR24       MMALEncodingType = C.MMAL_ENCODING_BGR24
	MMAL_ENCODING_BGR24_SLICE MMALEncodingType = C.MMAL_ENCODING_BGR24_SLICE
	MMAL_ENCODING_BGR32       MMALEncodingType = C.MMAL_ENCODING_BGR32
	MMAL_ENCODING_BGR32_SLICE MMALEncodingType = C.MMAL_ENCODING_BGR32_SLICE
)
